### ISSUE TITLE
[Question] Renovate Pro environment variables query

### ISSUE THREAD

**Issue by tigattack** [whitesource/renovate#101]
I’m currently configuring Renovate Pro on-premises using Docker Compose.
We use GitHub Enterprise hosted (github.com, not on-premises).
 
I’m wondering which of the following environment variables I should configure? The documentation is a little unclear and conflicts with some changelogs in the GitHub repository.
 
> RENOVATE_ENDPOINT
RENOVATE_TOKEN
RENOVATE_PLATFORM
GITHUB_APP_ID
GITHUB_APP_KEY
GITHUB_COM_TOKEN

Cheers.

**Comment by rarkins** [comment]
It's as per https://github.com/whitesource/renovate/blob/master/docs/configuration-github.md#configure-renovate-pro

If you can tell me what's unclear in the docs, we can update them.

**Comment by rarkins** [comment]
Does #102 clarify it for you?

**Comment by tigattack** [comment]
That does clarify it, thanks @rarkins. Could you quickly confirm for me that the compose snippet below is valid for hosted GHE?

```
      - RENOVATE_PLATFORM=github
      - RENOVATE_ENDPOINT=https://api.github.com/
    volumes:
      - "./renovate.private-key.pem:/usr/src/app/renovate.private-key.pem"
```

**Comment by rarkins** [comment]
yes, that's right

**Comment by tigattack** [comment]
Much appreciated, thank you 👍
