### ISSUE TITLE
[SBT] Version range question

### ISSUE THREAD

**Issue by waghanza** [whitesource/renovate#103]
Hi,

The bot has opened https://github.com/the-benchmarker/web-frameworks/pull/2563.

The idea is to replace `[0.21,0.22)` to `[0.21,0.20.21)`.

Assuming my very few skills on `scala` :

+ `[0.21,0.22)`, means **any** version in **0.21.x**
+ `[0.21,0.20.21)` means any version greater than **0.21** but (strictly) lower than **0.20.21**

I don't understand the idea of this `PR`

Regards,

**Comment by rarkins** [comment]
This seems like a bug in the core logic of Renovate, so please raise a bug report there: https://github.com/renovatebot/renovate/issues/new?template=3-Bug_report.md
