### ISSUE TITLE
Onboarding email specifies incorrect environment variable name

### ISSUE THREAD

**Issue by jono-paymark** [whitesource/renovate#105]
We've just registered so we can use the commercial version. This results in an onboarding email with this advice:

> Please follow the existing documentation for getting it set up and enter LICENSE_TYPE=commercial and LICENSE_NAME=<company name> in your environment to enable the unlocked version.

On applying this the application still ran in evaluation mode, however I discovered in this repo that the correct name is `LICENSE_MODE` rather than `LICENSE_TYPE` - and now it works correctly.
Also of note - the "existing documentation" link currently results in a 404.

**Comment by rarkins** [comment]
Thanks, I've sent a mail to a colleague to fix that up.
