### ISSUE TITLE
Support GitHub Enterprise hosted Presets

### ISSUE THREAD

**Issue by patrickmarabeas** [whitesource/renovate#43]
1) Single `renonvate.json` file existing in a GHE repo
2) Project repo with a `renovate.json` > `{ "extends": [ "github>ORG/REPOSITORY" ] }`

```
INFO: Repository has invalid config (repository=###/###)
"error": {
    "validationError": "Cannot find preset's package (github>ORG/REPOSITORY)"
}
```

Assuming Pro uses the same source; the GitHub api url assumes github.com:

renovate/lib/datasource/github/index.js
```
async function fetchJSONFile(repo, fileName) {
    const url = `https://api.github.com/repos/${repo}/contents/${fileName}`;
```

**Comment by rarkins** [comment]
Custom hosts are currently not supported. See https://github.com/renovatebot/renovate/issues/3019 and please +1 / comment if you have any ideas.

**Comment by rarkins** [comment]
https://github.com/whitesource/renovate/releases/tag/1.0.0
