### ISSUE TITLE
Support Helm Charts

### ISSUE THREAD

**Issue by patrickmarabeas** [whitesource/renovate#48]
Perhaps parse any `image` property in matched yaml files...

**Comment by rarkins** [comment]
Depends on https://github.com/renovatebot/renovate/issues/3414

**Comment by rarkins** [comment]
Please note also that there is an open PR right now for contributing a Helm chart for Pro itself: https://github.com/renovatebot/pro/pull/41

If you could review/comment on that, it would be helpful

**Comment by rarkins** [comment]
https://github.com/whitesource/renovate/releases/tag/1.0.0
