### ISSUE TITLE
Renovate Not updating Terraform Providers

### ISSUE THREAD

**Issue by moredhel** [whitesource/renovate#97]
### Which Renovate are you using?

Renovate Pro

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Yes:
https://github.com/moredhel/devops-test-repo/blob/master/renovate.log

### What would you like to do?

I am trying to maintain the terraform provider versions, but they are not being managed.
I have put together a simple repo which I am testing against:

https://github.com/moredhel/devops-test-repo/, it is a copy of an internal testing repo on my org. But it doesn't seem to be working.

As mentioned in the logs, it finds the provider.tf file, but doesn't find anything to update in it.

**Comment by rarkins** [comment]
The last Pro release is based off renovate@19.66.3 while providers were implemented in 19.83.0. We're aiming to get a new release out soon, will close/notify this issue then

**Comment by rarkins** [comment]
https://github.com/whitesource/renovate/releases/tag/1.0.0
