### ISSUE TITLE
Release notes contain mismatched versions and descriptions

### ISSUE THREAD

**Issue by tuckbick** [whitesource/renovate#99]
**What Renovate type are you using?**
Renovate Pro

**Describe the bug**
In a PR generated by Renovate, the version descriptions in the release notes appear to be mismatched.

The latest version is always correct, but previous releases all have descriptions that are off by 1.

**Did you see anything helpful in debug logs?**
N/A

**To Reproduce**
N/A

**Expected behavior**
Screenshot of the dependency's changelog:
<img width="896" alt="Screen Shot 2019-08-15 at 2 31 14 PM" src="https://user-images.githubusercontent.com/230995/63121161-6c3e3c00-bf69-11e9-93b1-0b54378bedf3.png">

**Screenshots**
Screenshot of the generated PR:
<img width="779" alt="Screen Shot 2019-08-15 at 2 30 08 PM" src="https://user-images.githubusercontent.com/230995/63121175-752f0d80-bf69-11e9-830d-6729fb51b173.png">

**Additional context**
Notice in the generated PR, the descriptions for `14.1.0` and `14.0.0` are the same, while in the repo's changelog they are different.

**Comment by rarkins** [comment]
Awesome! I've transferred this issue to the Pro repo and will close it with the next release

**Comment by rarkins** [comment]
https://github.com/whitesource/renovate/releases/tag/1.0.0
